Web/.eslintignore
Web/.eslintrc.js
Web/package.json
Web/src/App.tsx
Web/yarn.lock

`yarn lint` or `yarn lint --fix`

Add linting

---

Web/package.json
Web/src/App.tsx
Web/src/index.css
Web/yarn.lock

- colour variables
- body and heading fonts
- `yarn add styled-components @types/styled-components`

Add global styles

---

Web/.eslintrc.js

As discussed in our telegram chat, since typescript already handles this.

Rm prop-types rule

---

Web/.env.development
Web/.env.production
Web/src/components/create-room/index.tsx
Web/src/components/room/hooks/useErrorableChannel.ts

Add react env and link room page

---

Web/.env.production
Web/src/components/room/RoomTestPage.tsx
api/config/prod.exs
api/elixir_buildpack.config
api/lib/api_web/channels/room_channel.ex
deploy_gigalixir

Flow:
- Join channel `room:5432`
- When server receives message `"start"`, it will broadcast message `"start"` to all currently connected client
- When client send message `"result"` with payload `{"score": 500}`, server will take note
- After the deadline ends, server will broadcast message `"result"` with payload `{"result":[[50,"clientid1"], [100,"clientid2"]]}`
My tester is the RoomTestPage

Backend Implementation to show to our VC Investor

---

Web/src/components/join-room/index.tsx

Autofocus in game join PIN

---

Web/src/components/common/Modal.tsx

IMPT: Ensure that page using the modal has style `width: 100vw;`
Then you can use it like:
```
const [isModalOpen, setIsModalOpen] = useState(false);
<JoinRoomButton
type="submit"
disabled={gamePin.length < PIN_LENGTH}
onClick={() => setIsModalOpen(true)}
>
<Modal
isVisible={isModalOpen}
title="Permissions"
showCancel={false}
confirmationButtonText="Okay!"
onConfirm={() => setIsModalOpen(false)}
onCancel={() => setIsModalOpen(false)}
>
Hey we need your permission else you can't play BITCH.
</Modal>
```

Add modal component

---

Web/src/components/games/BalloonShake/GameDisplay.tsx
Web/src/components/games/BalloonShake/GamePrep.tsx
Web/src/components/games/BalloonShake/GameResults.tsx
Web/src/components/games/Countdown.tsx
Web/src/components/games/GameInstructions.tsx
Web/src/components/games/TimerDisplay.tsx

- style it according to mockup
- abstract out `TimerDisplay` since it will be a common component across games
- Should I make the timer maintain it's own state and update itself and accept a callback `onComplete`?  Wdyt?

Style balloon game

---

Web/src/components/common/forms/GamePinForm.tsx

Works for me on Chrome. lmk if this works for yall :)

Disable autocomplete for game pin

---

Web/src/components/create-room/CreateRoomPage.tsx
Web/src/components/join-room/JoinRoomPage.tsx
Web/src/components/room/PermissionsDialog.tsx
Web/src/components/room/hooks/permission/index.ts
Web/src/components/room/hooks/permission/useMotionPermissionsAccess.ts

Add permissions to create

---

.travis.yml
Web/package.json
Web/yarn.lock

Allows us to see the bundle size change to assess impact.
The bundle size change appears at the status checks

Add bundlewatch

---

.travis.yml

Trust me it works *looking at regex anxiously*

Remove hash from generated file in Travis

---

Web/src/components/create-room/HostRoom.tsx
Web/src/components/join-room/ParticipantRoom.tsx
Web/src/components/results-leaderboard/Leaderboard.tsx
Web/src/components/results-leaderboard/Results.tsx
Web/src/components/results-leaderboard/index.tsx
Web/src/components/room/CommonRoom.tsx

To be merged into `results-page`. 
No need for review here, we can do it all on the `results-page` branch :)

Results Page Staging

---

.travis.yml
Web/package.json
Web/src/components/create-room/GameSequenceGenerator.ts
Web/src/components/create-room/HostRoom.tsx
Web/yarn.lock

Round robin

---

Web/.env.development
Web/src/components/games/MentalSums/NumKeypad.tsx

In Firefox Android it wasn't working

Solve the problem of rapid touch in successions not registering

---

Web/src/components/games/BalloonShake/index.tsx
Web/src/components/games/GameStates.ts
Web/src/components/games/MentalSums/index.tsx
Web/src/components/games/PandaSequence/index.tsx

Add COMPLETED state to prevent re-creation of TimesUp

---

Web/src/components/games/MentalSums/ProblemGen.ts

Fix generator functions in useState

---

.travis.yml

Add stylelint to Travis

---

.travis.yml

Before https://github.com/bundlewatch/bundlewatch/pull/62 is merged

Fix wrong bundlewatch inferring travis branches

---

Web/src/components/create-room/CreateRoomPage.tsx
Web/src/components/join-room/JoinRoomPage.tsx
Web/src/components/join-room/ParticipantRoom.tsx
Web/src/components/room/CommonRoom.tsx
Web/src/components/room/ErrorDisplay.tsx
Web/src/components/room/comm/Comm.ts
Web/src/components/room/comm/Errors.ts
Web/src/components/room/comm/phoenix/PhoenixComm.ts

Change host leaving to be an error on client side

---

Web/src/components/join-room/JoinRoomForm.tsx
Web/src/components/room/comm/Comm.ts
Web/src/components/room/comm/phoenix/PhoenixComm.ts

Clear error when pressing back in join room page

---

Web/src/components/games/BalloonShake/BalloonShakeInstructions.tsx
Web/src/components/games/BalloonShake/index.tsx
Web/src/components/games/GameInstructions.tsx
Web/src/components/games/MentalSums/MentalSumsInstructions.tsx
Web/src/components/games/MentalSums/index.tsx
Web/src/components/games/PandaSequence/PandaSequenceInstructions.tsx
Web/src/components/games/PandaSequence/index.tsx
Web/src/components/room/CommonRoom.tsx

Fix #188 
- Before ready:
- After ready (waiting):

Merge instructions & 'I am ready' screen

---

Web/src/components/create-room/CreateRoomPage.tsx

The previous pinda was too huge

Change create form icon to pinda head

---

Web/src/components/join-room/ParticipantRoom.tsx
Web/src/components/room/CommonRoom.tsx

Add quit links

---

Web/package.json
Web/src/index.tsx
Web/yarn.lock

By polyfilling `Object.fromEntries` because iOS only have that since iOS 12.2
This might fix Samsung Internet too since it doesn't have `Object.fromEntries` too

Fix game stuck at connecting due to missing Object.fromEntries 
